// countries.geo.json → src/mapdata.js (等距円筒図法・簡略化済みSVGパス)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const W = 1000;
const LAT_TOP = 85, LAT_BOT = -60;
const H = Math.round(W * (LAT_TOP - LAT_BOT) / 360); // 403

const px = ([lon, lat]) => [
  (lon + 180) / 360 * W,
  (LAT_TOP - lat) / (LAT_TOP - LAT_BOT) * H,
];

// Douglas-Peucker
function simplify(pts, tol) {
  if (pts.length < 3) return pts;
  const keep = new Uint8Array(pts.length);
  keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = pts[a], [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay;
    const len2 = dx * dx + dy * dy || 1e-12;
    let maxD = -1, maxI = -1;
    for (let i = a + 1; i < b; i++) {
      const t = Math.max(0, Math.min(1, ((pts[i][0] - ax) * dx + (pts[i][1] - ay) * dy) / len2));
      const ex = ax + t * dx - pts[i][0], ey = ay + t * dy - pts[i][1];
      const d = ex * ex + ey * ey;
      if (d > maxD) { maxD = d; maxI = i; }
    }
    if (maxD > tol * tol) { keep[maxI] = 1; stack.push([a, maxI], [maxI, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}

const ringArea = (pts) => {
  let s = 0;
  for (let i = 0; i < pts.length; i++) {
    const [x1, y1] = pts[i], [x2, y2] = pts[(i + 1) % pts.length];
    s += x1 * y2 - x2 * y1;
  }
  return Math.abs(s / 2);
};

function toPath(rings, tol, minArea) {
  const parts = [];
  for (const ring of rings) {
    let pts = ring.map(px);
    if (ringArea(pts) < minArea) continue;
    pts = simplify(pts, tol);
    if (pts.length < 3) continue;
    parts.push('M' + pts.map(p => `${Math.round(p[0] * 10) / 10} ${Math.round(p[1] * 10) / 10}`).join('L') + 'Z');
  }
  return parts.join('');
}

// 課題マップ対象国 (ISO3 → region id)
const REGION_IDS = { JPN: 'jp', KOR: 'kr', CHN: 'cn', TWN: 'tw', PRK: 'kp' };

const geo = JSON.parse(readFileSync(join(ROOT, 'tools', 'countries.geo.json'), 'utf8'));
const world = [];
const regions = {};

for (const f of geo.features) {
  const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
  const rid = REGION_IDS[f.id];
  if (rid && !regions[rid]) regions[rid] = { paths: [], big: null, bigArea: -1, x0: 1e9, y0: 1e9, x1: -1e9, y1: -1e9 };
  for (const poly of polys) {
    const outer = poly[0]; // 穴は無視(この縮尺では見えない)
    const d = toPath([outer], rid ? 0.35 : 0.7, rid ? 1.2 : 4);
    if (!d) continue;
    if (!rid) { world.push(d); continue; }
    const R = regions[rid];
    R.paths.push(d);
    const pts = outer.map(px), a = ringArea(pts);
    if (a > R.bigArea) { R.bigArea = a; R.big = pts; }
    for (const [x, y] of pts) {
      R.x0 = Math.min(R.x0, x); R.y0 = Math.min(R.y0, y);
      R.x1 = Math.max(R.x1, x); R.y1 = Math.max(R.y1, y);
    }
  }
}

const regionsOut = {};
for (const [rid, R] of Object.entries(regions)) {
  let cx = 0, cy = 0;
  for (const [x, y] of R.big) { cx += x; cy += y; }
  cx /= R.big.length; cy /= R.big.length;
  regionsOut[rid] = {
    paths: R.paths,
    center: { x: +cx.toFixed(1), y: +cy.toFixed(1) },
    bbox: { x: +R.x0.toFixed(1), y: +R.y0.toFixed(1), w: +(R.x1 - R.x0).toFixed(1), h: +(R.y1 - R.y0).toFixed(1) },
  };
}

const out = `// generated by tools/build-map.mjs — Natural Earth由来 (public domain)
const WORLD_MAP = {
  w: ${W}, h: ${H},
  land: ${JSON.stringify(world)},
  regions: ${JSON.stringify(regionsOut)},
};
if (typeof module !== 'undefined') module.exports = { WORLD_MAP };
`;
writeFileSync(join(ROOT, 'src', 'mapdata.js'), out);
console.log(`mapdata.js: land=${world.length} regions=${Object.entries(regionsOut).map(([k, r]) => `${k}(${r.paths.length}paths c=${r.center.x},${r.center.y} bbox=${r.bbox.w}x${r.bbox.h})`).join(' ')} size=${(out.length / 1024).toFixed(0)}KB`);
